spring:
    profiles:
        active: dev
    server:
        port: 8085
        contextPath: /smartturn
        httpConnectionTimeout: 200000
        maximumThreads: 200
        maximumHeaderSize: 32768
        redirectPort: 8443
        socket:
            bufferSize: 2048
            rxBufSize: 512
            appReadBufSize: 512
            appWriteBufSize: 512
---
spring: 
    profiles: dev
    datasource: 
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/smartturndb
        username: smartturnuser
        password: Llbtck5NKfMroK32
        dataSourceClassName: javax.sql.DataSource
        driver: com.mysql.jdbc.Driver
        hikari:
            data-source-properties:
                autocommit: false
                minimumIdle: 5
                maximumPoolSize: 20
                idleTimeout: 30000
                poolName: SpringBootJPAHikariCP
                maxLifetime: 2000000
                connectionTimeout: 30000
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
                connectionTestQuery: SELECT 1
                levelHikariConfig: DEBUG
    jpa:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
        format-sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: net.sf.ehcache.hibernate.EhCacheRegionFactory
            hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
            hibernate.javax.cache.provider: org.ehcache.jsr107.EhcacheCachingProvider
            hibernate.level.SQL: DEBUG
            hibernate.level.type.sql.BasicBinder: TRACE 
security:
  basic:
    enabled: false
endpoints: 
    metrics:
        sensitive: false
    shutdown:
        enabled: true
management:
    port: 8085
    context-path: '/management'
server:
    port: 8085
application:

