spring:
  profiles:
    active: dev
---
server:
  port: 8085
  servlet:
    context-path: /smartturn
    application-display-name: smartturn
---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/smartturndb
    username: smartturnuser
    password: Llbtck5NKfMroK32
    driver-class-name: com.mysql.jdbc.Driver
    hikari: 
      data-source-properties:
         autocommit: false
         minimumIdle: 5
         maximumPoolSize: 20
         idleTimeout: 30000
         poolName: SpringBootJPAHikariCP
         maxLifetime: 2000000
         connectionTimeout: 30000
         cachePrepStmts: true
         prepStmtCacheSize: 250
         prepStmtCacheSqlLimit: 2048
         useServerPrepStmts: true
         connectionTestQuery: SELECT 1
         levelHikariConfig: DEBUG
